// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/employee.proto

package com.demo.producer.proto;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:employee.Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string department = 3;</code>
     * @return The department.
     */
    java.lang.String getDepartment();
    /**
     * <code>string department = 3;</code>
     * @return The bytes for department.
     */
    com.google.protobuf.ByteString
        getDepartmentBytes();

    /**
     * <code>double salary = 4;</code>
     * @return The salary.
     */
    double getSalary();
  }
  /**
   * Protobuf type {@code employee.Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:employee.Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      name_ = "";
      department_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.producer.proto.EmployeeProto.internal_static_employee_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.producer.proto.EmployeeProto.internal_static_employee_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.producer.proto.EmployeeProto.Employee.class, com.demo.producer.proto.EmployeeProto.Employee.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPARTMENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object department_ = "";
    /**
     * <code>string department = 3;</code>
     * @return The department.
     */
    @java.lang.Override
    public java.lang.String getDepartment() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        department_ = s;
        return s;
      }
    }
    /**
     * <code>string department = 3;</code>
     * @return The bytes for department.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDepartmentBytes() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        department_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALARY_FIELD_NUMBER = 4;
    private double salary_ = 0D;
    /**
     * <code>double salary = 4;</code>
     * @return The salary.
     */
    @java.lang.Override
    public double getSalary() {
      return salary_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(department_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, department_);
      }
      if (java.lang.Double.doubleToRawLongBits(salary_) != 0) {
        output.writeDouble(4, salary_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(department_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, department_);
      }
      if (java.lang.Double.doubleToRawLongBits(salary_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salary_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.producer.proto.EmployeeProto.Employee)) {
        return super.equals(obj);
      }
      com.demo.producer.proto.EmployeeProto.Employee other = (com.demo.producer.proto.EmployeeProto.Employee) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDepartment()
          .equals(other.getDepartment())) return false;
      if (java.lang.Double.doubleToLongBits(getSalary())
          != java.lang.Double.doubleToLongBits(
              other.getSalary())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDepartment().hashCode();
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSalary()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.producer.proto.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.producer.proto.EmployeeProto.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code employee.Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:employee.Employee)
        com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.producer.proto.EmployeeProto.internal_static_employee_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.producer.proto.EmployeeProto.internal_static_employee_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.producer.proto.EmployeeProto.Employee.class, com.demo.producer.proto.EmployeeProto.Employee.Builder.class);
      }

      // Construct using com.demo.producer.proto.EmployeeProto.Employee.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        department_ = "";
        salary_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.producer.proto.EmployeeProto.internal_static_employee_Employee_descriptor;
      }

      @java.lang.Override
      public com.demo.producer.proto.EmployeeProto.Employee getDefaultInstanceForType() {
        return com.demo.producer.proto.EmployeeProto.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.producer.proto.EmployeeProto.Employee build() {
        com.demo.producer.proto.EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.producer.proto.EmployeeProto.Employee buildPartial() {
        com.demo.producer.proto.EmployeeProto.Employee result = new com.demo.producer.proto.EmployeeProto.Employee(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.demo.producer.proto.EmployeeProto.Employee result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.department_ = department_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.salary_ = salary_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.producer.proto.EmployeeProto.Employee) {
          return mergeFrom((com.demo.producer.proto.EmployeeProto.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.producer.proto.EmployeeProto.Employee other) {
        if (other == com.demo.producer.proto.EmployeeProto.Employee.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDepartment().isEmpty()) {
          department_ = other.department_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getSalary() != 0D) {
          setSalary(other.getSalary());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                department_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                salary_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object department_ = "";
      /**
       * <code>string department = 3;</code>
       * @return The department.
       */
      public java.lang.String getDepartment() {
        java.lang.Object ref = department_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          department_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string department = 3;</code>
       * @return The bytes for department.
       */
      public com.google.protobuf.ByteString
          getDepartmentBytes() {
        java.lang.Object ref = department_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          department_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string department = 3;</code>
       * @param value The department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartment(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        department_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string department = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDepartment() {
        department_ = getDefaultInstance().getDepartment();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string department = 3;</code>
       * @param value The bytes for department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        department_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private double salary_ ;
      /**
       * <code>double salary = 4;</code>
       * @return The salary.
       */
      @java.lang.Override
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>double salary = 4;</code>
       * @param value The salary to set.
       * @return This builder for chaining.
       */
      public Builder setSalary(double value) {
        
        salary_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double salary = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalary() {
        bitField0_ = (bitField0_ & ~0x00000008);
        salary_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:employee.Employee)
    }

    // @@protoc_insertion_point(class_scope:employee.Employee)
    private static final com.demo.producer.proto.EmployeeProto.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.producer.proto.EmployeeProto.Employee();
    }

    public static com.demo.producer.proto.EmployeeProto.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.producer.proto.EmployeeProto.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmployeeListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:employee.EmployeeList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    java.util.List<com.demo.producer.proto.EmployeeProto.Employee> 
        getEmployeesList();
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    com.demo.producer.proto.EmployeeProto.Employee getEmployees(int index);
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    int getEmployeesCount();
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    java.util.List<? extends com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder> 
        getEmployeesOrBuilderList();
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder getEmployeesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code employee.EmployeeList}
   */
  public static final class EmployeeList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:employee.EmployeeList)
      EmployeeListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmployeeList.newBuilder() to construct.
    private EmployeeList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmployeeList() {
      employees_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EmployeeList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.producer.proto.EmployeeProto.internal_static_employee_EmployeeList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.producer.proto.EmployeeProto.internal_static_employee_EmployeeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.producer.proto.EmployeeProto.EmployeeList.class, com.demo.producer.proto.EmployeeProto.EmployeeList.Builder.class);
    }

    public static final int EMPLOYEES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.demo.producer.proto.EmployeeProto.Employee> employees_;
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.demo.producer.proto.EmployeeProto.Employee> getEmployeesList() {
      return employees_;
    }
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder> 
        getEmployeesOrBuilderList() {
      return employees_;
    }
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    @java.lang.Override
    public int getEmployeesCount() {
      return employees_.size();
    }
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    @java.lang.Override
    public com.demo.producer.proto.EmployeeProto.Employee getEmployees(int index) {
      return employees_.get(index);
    }
    /**
     * <code>repeated .employee.Employee employees = 1;</code>
     */
    @java.lang.Override
    public com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder getEmployeesOrBuilder(
        int index) {
      return employees_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < employees_.size(); i++) {
        output.writeMessage(1, employees_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < employees_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, employees_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.producer.proto.EmployeeProto.EmployeeList)) {
        return super.equals(obj);
      }
      com.demo.producer.proto.EmployeeProto.EmployeeList other = (com.demo.producer.proto.EmployeeProto.EmployeeList) obj;

      if (!getEmployeesList()
          .equals(other.getEmployeesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEmployeesCount() > 0) {
        hash = (37 * hash) + EMPLOYEES_FIELD_NUMBER;
        hash = (53 * hash) + getEmployeesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.producer.proto.EmployeeProto.EmployeeList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.producer.proto.EmployeeProto.EmployeeList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code employee.EmployeeList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:employee.EmployeeList)
        com.demo.producer.proto.EmployeeProto.EmployeeListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.producer.proto.EmployeeProto.internal_static_employee_EmployeeList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.producer.proto.EmployeeProto.internal_static_employee_EmployeeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.producer.proto.EmployeeProto.EmployeeList.class, com.demo.producer.proto.EmployeeProto.EmployeeList.Builder.class);
      }

      // Construct using com.demo.producer.proto.EmployeeProto.EmployeeList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
        } else {
          employees_ = null;
          employeesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.producer.proto.EmployeeProto.internal_static_employee_EmployeeList_descriptor;
      }

      @java.lang.Override
      public com.demo.producer.proto.EmployeeProto.EmployeeList getDefaultInstanceForType() {
        return com.demo.producer.proto.EmployeeProto.EmployeeList.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.producer.proto.EmployeeProto.EmployeeList build() {
        com.demo.producer.proto.EmployeeProto.EmployeeList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.producer.proto.EmployeeProto.EmployeeList buildPartial() {
        com.demo.producer.proto.EmployeeProto.EmployeeList result = new com.demo.producer.proto.EmployeeProto.EmployeeList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.demo.producer.proto.EmployeeProto.EmployeeList result) {
        if (employeesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            employees_ = java.util.Collections.unmodifiableList(employees_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.employees_ = employees_;
        } else {
          result.employees_ = employeesBuilder_.build();
        }
      }

      private void buildPartial0(com.demo.producer.proto.EmployeeProto.EmployeeList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.producer.proto.EmployeeProto.EmployeeList) {
          return mergeFrom((com.demo.producer.proto.EmployeeProto.EmployeeList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.producer.proto.EmployeeProto.EmployeeList other) {
        if (other == com.demo.producer.proto.EmployeeProto.EmployeeList.getDefaultInstance()) return this;
        if (employeesBuilder_ == null) {
          if (!other.employees_.isEmpty()) {
            if (employees_.isEmpty()) {
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEmployeesIsMutable();
              employees_.addAll(other.employees_);
            }
            onChanged();
          }
        } else {
          if (!other.employees_.isEmpty()) {
            if (employeesBuilder_.isEmpty()) {
              employeesBuilder_.dispose();
              employeesBuilder_ = null;
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000001);
              employeesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEmployeesFieldBuilder() : null;
            } else {
              employeesBuilder_.addAllMessages(other.employees_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.demo.producer.proto.EmployeeProto.Employee m =
                    input.readMessage(
                        com.demo.producer.proto.EmployeeProto.Employee.parser(),
                        extensionRegistry);
                if (employeesBuilder_ == null) {
                  ensureEmployeesIsMutable();
                  employees_.add(m);
                } else {
                  employeesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.demo.producer.proto.EmployeeProto.Employee> employees_ =
        java.util.Collections.emptyList();
      private void ensureEmployeesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          employees_ = new java.util.ArrayList<com.demo.producer.proto.EmployeeProto.Employee>(employees_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.demo.producer.proto.EmployeeProto.Employee, com.demo.producer.proto.EmployeeProto.Employee.Builder, com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder> employeesBuilder_;

      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public java.util.List<com.demo.producer.proto.EmployeeProto.Employee> getEmployeesList() {
        if (employeesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(employees_);
        } else {
          return employeesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public int getEmployeesCount() {
        if (employeesBuilder_ == null) {
          return employees_.size();
        } else {
          return employeesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public com.demo.producer.proto.EmployeeProto.Employee getEmployees(int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);
        } else {
          return employeesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder setEmployees(
          int index, com.demo.producer.proto.EmployeeProto.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.set(index, value);
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder setEmployees(
          int index, com.demo.producer.proto.EmployeeProto.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.set(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder addEmployees(com.demo.producer.proto.EmployeeProto.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder addEmployees(
          int index, com.demo.producer.proto.EmployeeProto.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(index, value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder addEmployees(
          com.demo.producer.proto.EmployeeProto.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder addEmployees(
          int index, com.demo.producer.proto.EmployeeProto.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder addAllEmployees(
          java.lang.Iterable<? extends com.demo.producer.proto.EmployeeProto.Employee> values) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, employees_);
          onChanged();
        } else {
          employeesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder clearEmployees() {
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          employeesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public Builder removeEmployees(int index) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.remove(index);
          onChanged();
        } else {
          employeesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public com.demo.producer.proto.EmployeeProto.Employee.Builder getEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder getEmployeesOrBuilder(
          int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);  } else {
          return employeesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public java.util.List<? extends com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder> 
           getEmployeesOrBuilderList() {
        if (employeesBuilder_ != null) {
          return employeesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(employees_);
        }
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public com.demo.producer.proto.EmployeeProto.Employee.Builder addEmployeesBuilder() {
        return getEmployeesFieldBuilder().addBuilder(
            com.demo.producer.proto.EmployeeProto.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public com.demo.producer.proto.EmployeeProto.Employee.Builder addEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().addBuilder(
            index, com.demo.producer.proto.EmployeeProto.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .employee.Employee employees = 1;</code>
       */
      public java.util.List<com.demo.producer.proto.EmployeeProto.Employee.Builder> 
           getEmployeesBuilderList() {
        return getEmployeesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.demo.producer.proto.EmployeeProto.Employee, com.demo.producer.proto.EmployeeProto.Employee.Builder, com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder> 
          getEmployeesFieldBuilder() {
        if (employeesBuilder_ == null) {
          employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.demo.producer.proto.EmployeeProto.Employee, com.demo.producer.proto.EmployeeProto.Employee.Builder, com.demo.producer.proto.EmployeeProto.EmployeeOrBuilder>(
                  employees_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          employees_ = null;
        }
        return employeesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:employee.EmployeeList)
    }

    // @@protoc_insertion_point(class_scope:employee.EmployeeList)
    private static final com.demo.producer.proto.EmployeeProto.EmployeeList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.producer.proto.EmployeeProto.EmployeeList();
    }

    public static com.demo.producer.proto.EmployeeProto.EmployeeList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmployeeList>
        PARSER = new com.google.protobuf.AbstractParser<EmployeeList>() {
      @java.lang.Override
      public EmployeeList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EmployeeList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmployeeList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.producer.proto.EmployeeProto.EmployeeList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employee_EmployeeList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employee_EmployeeList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/employee.proto\022\010employe" +
      "e\"H\n\010Employee\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022" +
      "\022\n\ndepartment\030\003 \001(\t\022\016\n\006salary\030\004 \001(\001\"5\n\014E" +
      "mployeeList\022%\n\temployees\030\001 \003(\0132\022.employe" +
      "e.EmployeeB(\n\027com.demo.producer.protoB\rE" +
      "mployeeProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_employee_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employee_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Department", "Salary", });
    internal_static_employee_EmployeeList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_employee_EmployeeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employee_EmployeeList_descriptor,
        new java.lang.String[] { "Employees", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
